# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Create a dummy keys file for google-project-id1 to allow initialization
RUN mkdir -p keys && \
    echo '{"client_email": "dummy@example.com", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEv...dummy...\n-----END PRIVATE KEY-----", "project_id": "google-project-id1"}' > keys/google-project-id1.json

# Build the project
RUN npm run build

CMD ["node", "build/index.js"]
